# defines the git repositroy to use, options:
# "CODECOMMIT" - will create a new codecommit repo with name specified in repoName
# "CODECOMMIT_PROVIDED" - will expect a codecommit repository in the account with name specified in repoName
# "GITHUB" - will use an existing codestar connection for GitHub source, checkout README.MD, for instructions
repoType: GITHUB
# the repo where the pipeline should pull its source from
repoName: mlops-at-edge-for-quality-inspection
# the CodestarConnectionArn for your GitHub repository
githubConnectionArn: arn:aws:codestar-connections:ap-northeast-1:202856454646:connection/c3307e3b-e16d-48d3-a01d-86be390319ce
# the GitHub repo owner
githubRepoOwner: RI-Keiichi-yokoyama
# the git branch to use
branchName: main
